### ISSUE TITLE
Provide option to set header title/tooltip

### ISSUE THREAD

**Issue by amir-hadzic** [sematext/sematable#24]

**Comment by pgoldweic** [comment]
This would be great to have. Thanks!

**Comment by pgoldweic** [comment]
Is this supposed to be already in place? I've tried using it by adding a 'title' property to my headers array, but it does not seem to have an effect. (note: I bumped version to 1.4.1)

**Comment by amir-hadzic** [comment]
It should be working, you can test it out in storybook (npm run storybook). Can you post your column definitions?

**Comment by amir-hadzic** [comment]
I did notice that bootstrap tooltip is used if it's defined on non-sortable column, and non-bootstrap tooltip is used if defined on sortable column. I'll fix that.

**Comment by pgoldweic** [comment]
Oh, I see. Glad you noticed. Thanks!

**Comment by pgoldweic** [comment]
Thanks again for working on this. However, I have to say that it is still not working for me (I bumped version to 1.4.2). I may be missing something here, but what is it? I've added a 'title' property to every header, as follows: 
    const headers = {
		field1: { sortKey: "student", name: "student", searchable: true, title: "Student's Id"},
                field2: {sortKey:"name",name:"name",searchable: true: title: "Student's name"}
                }

Then I render the table in the following way:

    <Table condensed striped bordered hover responsive>
        <thead>
	    <tr>
	        <SortableHeader className="narrowfield" {...student} />
	        <SortableHeader className="narrowfield" {...name} />
	    </tr>
        </thead>
	<tbody>{rows}</tbody>

What could be wrong?
